#############################################
# Server Configurations
#############################################

spring.application.name: file-download-service
server.port: 8080

#############################################
# Download Configurations
#############################################

download.url: http://localhost:8000/download

#############################################
# S3 Configurations
#############################################

object-storage:
  endpoint: http://localhost:9000
  access-key: admin
  access-secret: password
  bucket: storage

#############################################
# Redis Configurations
#############################################

spring.data.redis:
  host: localhost
  port: 6379
  password: APHGGBHQkHdgD49pjuBfkyKCKZAsrr
  database: 0
