version: '3.9'

services:
  redis:
    container_name: redis_server
    image: redis:7.2.4-alpine
    volumes:
      - ./storage:/data
    command: redis-server --save 20 1 --loglevel warning --requirepass APHGGBHQkHdgD49pjuBfkyKCKZAsrr
