version: '3.9'

services:
  nginx:
    container_name: nginx_gateway
    image: openresty/openresty:1.25.3.1-3-alpine
    ports:
      - "8000:8000"
    volumes:
      - ./nginx-lua.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
