version: '3.9'

services:
  minio:
    container_name: minio_server
    image: minio/minio:RELEASE.2024-04-18T19-09-19Z
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./storage:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    command: server --console-address ":9001" /data
